# protocol file
# mime text/*
# action launch nvim $FILE_PATH

protocol file
mime image/*
action launch --type=overlay kitty +kitten icat --hold $FILE_PATH

# protocol file
# mime markdown/*
# action launch --type=overlay kitty +kitten edit-in-kitty $FILE_PATH
