preload = $XDG_PICTURES_DIR/Wallpapers/EvaWallpaper.jpg
preload = $XDG_PICTURES_DIR/Wallpapers/RainyWallpaper.png
preload = $XDG_PICTURES_DIR/Wallpapers/BeachWallpaper.jpg
preload = $XDG_PICTURES_DIR/Wallpapers/SnowyWallpaper.png
wallpaper = , $XDG_PICTURES_DIR/Wallpapers/BeachWallpaper.jpg

