general {
    lock_cmd = pidof hyprlock || sh /home/hsiao/.config/hypr/.hyprlock.sh
    # unlock_cmd = notify-send -t 5000  "Unlocked"      # same as above, but unlock
	 # command ran before sleep
    # before_sleep_cmd = notify-send -t 5000 -i /home/hsiao/.local/share/icons/Papirus-Dark/64x64/apps/ares.svg "Sleeping"
	 # after_sleep_cmd = notify-send -t 5000 "Not sleeping"  # command ran after sleep
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # whether to ignore systemd-inhibit --what=idle inhibitors
}

# listener {
# 	timeout = 300                            # in seconds
# 	# command to run when timeout has passed
#    on-timeout = notify-send -t 5000 -i /home/hsiao/.local/share/icons/Papirus-Dark/64x64/apps/alarm-clock.svg "Detetced idle"
# 	on-resume = notify-send -t 5000 "No longer idle"  # command to run when activity is detected after timeout has fired.
# }

listener {
   timeout = 600                             # in seconds
   on-timeout = loginctl lock-session
   #on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}

listener {
   timeout = 3600                            # in seconds
   on-timeout = hyprctl dispatch exit
   #on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}
