preload = /home/hsiao/Pictures/Wallpapers/EvaWallpaper.jpg
preload = /home/hsiao/Pictures/Wallpapers/RainyWallpaper.png
preload = /home/hsiao/Pictures/Wallpapers/BeachWallpaper.jpg
preload = /home/hsiao/Pictures/Wallpapers/SnowyWallpaper.png
wallpaper = , /home/hsiao/Pictures/Wallpapers/BeachWallpaper.jpg

