[Interface]
PrivateKey = eGB1xQxHyTlLEBwHMPkBF32u3aOXU+XEEHt0iB7pyH4=
Address = 10.21.55.2/24, fd11:5ee:bad:c0de::a15:3702/64
DNS = 9.9.9.9, 149.112.112.112

[Peer]
PublicKey = Ie3+aCFp+g2zp5O7e681nGW9iRNeKeOw3bh08ZfmeQA=
PresharedKey = 1vU5jOiLCmdYLYXZ1dw/w4zU1Z9qtwgMvdGc9+wiNno=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = hsiaoddns.myddns.me:51820
